package com.venturelens.utils;

import com.venturelens.model.Venture;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.text.NumberFormat;
import java.time.LocalDate;
import java.util.Locale;

/**
 * Exporter for PitchCraft 10-slide investor blueprints.
 * Strictly uses java.nio.file and standard string formatting without third-party template engines.
 */
public class ReportExporter {

    private static final NumberFormat CURRENCY = NumberFormat.getCurrencyInstance(new Locale("en", "IN"));

    /**
     * Exports a 10-slide startup blueprint as structured Markdown (.md).
     */
    public static Path exportToMarkdown(Venture v, String destinationPath) throws IOException {
        StringBuilder sb = new StringBuilder();
        sb.append("# ").append(v.getStartupName()).append(" — PitchCraft Investor Blueprint\n\n");
        sb.append("> Generated by VentureLens Decision Intelligence Suite on ").append(LocalDate.now()).append("\n");
        sb.append("> Decision Tier: **").append(v.getDecisionTier()).append("** | Composite Score: **")
          .append(v.getOverallScore()).append("/100**\n\n");
        sb.append("---\n\n");

        sb.append("## Slide 1: Executive Summary & Vision\n");
        sb.append("- **Startup Name:** ").append(v.getStartupName()).append("\n");
        sb.append("- **Target Customer:** ").append(v.getTargetCustomer()).append("\n");
        sb.append("- **Decision Intelligence Rating:** ").append(v.getDecisionTier()).append(" (")
          .append(v.getOverallScore()).append("/100)\n\n");

        sb.append("## Slide 2: The Core Problem\n");
        sb.append(v.getProblemStatement()).append("\n\n");

        sb.append("## Slide 3: Proposed Solution & Defensibility\n");
        sb.append(v.getProposedSolution()).append("\n\n");

        sb.append("## Slide 4: Target Market & Validation Metrics\n");
        sb.append("- **Market Readiness Score:** ").append(v.getMarketScore()).append("/100\n");
        sb.append("- **Feasibility Score:** ").append(v.getFeasibilityScore()).append("/100\n");
        sb.append("- **Competitive Advantage Score:** ").append(v.getCompetitionScore()).append("/100\n");
        sb.append("- **Concept Depth:** ").append(v.getDepthScore()).append("/100\n\n");

        sb.append("## Slide 5: Business Model & Monetization\n");
        sb.append(v.getBusinessModel()).append("\n\n");

        sb.append("## Slide 6: SWOT Analysis Matrix\n");
        sb.append("- **Strengths:** ").append(v.getStrengths()).append("\n");
        sb.append("- **Weaknesses:** ").append(v.getWeaknesses()).append("\n");
        sb.append("- **Opportunities:** ").append(v.getOpportunities()).append("\n");
        sb.append("- **Threats:** ").append(v.getThreats()).append("\n\n");

        sb.append("## Slide 7: Critical Failure Risks & Mitigation\n");
        sb.append(v.getCriticalRisks()).append("\n\n");

        sb.append("## Slide 8: CapTable & Ownership Distribution\n");
        sb.append("- **Founder Shares:** ").append(v.getFounderEquity()).append("%\n");
        sb.append("- **ESOP Talent Pool:** ").append(v.getEsopPool()).append("%\n");
        sb.append("- **Investor Equity:** ").append(v.getInvestorEquity()).append("%\n\n");

        sb.append("## Slide 9: Valuation & Investment Round\n");
        sb.append("- **Pre-Money Valuation:** ").append(CURRENCY.format(v.getPreMoneyValuation())).append("\n");
        sb.append("- **Investment Ask:** ").append(CURRENCY.format(v.getInvestmentAmount())).append("\n");
        sb.append("- **Post-Money Valuation:** ").append(CURRENCY.format(v.getPostMoneyValuation())).append("\n\n");

        sb.append("## Slide 10: BurnWatch Financial Health & Runway\n");
        sb.append("- **Current Cash Balance:** ").append(CURRENCY.format(v.getCurrentCashBalance())).append("\n");
        sb.append("- **Net Monthly Burn:** ").append(CURRENCY.format(v.getMonthlyBurn())).append("/mo\n");
        sb.append("- **Survival Runway:** ").append(v.getRunwayMonths()).append(" Months\n");

        Path path = Paths.get(destinationPath);
        Files.writeString(path, sb.toString(), StandardCharsets.UTF_8);
        return path;
    }

    /**
     * Exports a 10-slide startup blueprint as a printable HTML/CSS document (@media print for 1-click PDF).
     */
    public static Path exportToPrintableHtml(Venture v, String destinationPath) throws IOException {
        StringBuilder html = new StringBuilder();
        html.append("<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n");
        html.append("<meta charset=\"UTF-8\">\n");
        html.append("<title>").append(v.getStartupName()).append(" — PitchCraft Blueprint</title>\n");
        html.append("<style>\n");
        html.append("  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; margin: 0; padding: 40px; color: #1E293B; background: #F8FAFC; }\n");
        html.append("  .container { max-width: 860px; margin: 0 auto; background: #FFFFFF; padding: 48px; border-radius: 12px; box-shadow: 0 4px 20px rgba(0,0,0,0.06); border: 1px solid #E2E8F0; }\n");
        html.append("  .header { border-bottom: 2px solid #4F46E5; padding-bottom: 20px; margin-bottom: 30px; display: flex; justify-content: space-between; align-items: flex-end; }\n");
        html.append("  h1 { margin: 0; color: #0F172A; font-size: 28px; }\n");
        html.append("  .badge { display: inline-block; padding: 6px 14px; border-radius: 9999px; font-weight: 700; font-size: 13px; text-transform: uppercase; background: #EEF2FF; color: #4F46E5; border: 1px solid #C7D2FE; }\n");
        html.append("  .slide-card { background: #F8FAFC; border: 1px solid #E2E8F0; border-radius: 8px; padding: 20px; margin-bottom: 20px; page-break-inside: avoid; }\n");
        html.append("  .slide-title { font-size: 16px; font-weight: 700; color: #4F46E5; margin-top: 0; margin-bottom: 12px; }\n");
        html.append("  .grid-2 { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; }\n");
        html.append("  .metric-box { background: #FFFFFF; border: 1px solid #E2E8F0; padding: 12px; border-radius: 6px; }\n");
        html.append("  .metric-lbl { font-size: 11px; text-transform: uppercase; color: #64748B; font-weight: 600; }\n");
        html.append("  .metric-val { font-size: 18px; font-weight: 700; color: #0F172A; margin-top: 4px; }\n");
        html.append("  @media print {\n");
        html.append("    body { background: #FFFFFF; padding: 0; }\n");
        html.append("    .container { border: none; box-shadow: none; padding: 20px; max-width: 100%; }\n");
        html.append("    .slide-card { page-break-inside: avoid; border-color: #CBD5E1; }\n");
        html.append("  }\n");
        html.append("</style>\n</head>\n<body>\n");

        html.append("<div class=\"container\">\n");
        html.append("  <div class=\"header\">\n");
        html.append("    <div>\n");
        html.append("      <h1>").append(v.getStartupName()).append("</h1>\n");
        html.append("      <div style=\"color: #64748B; font-size: 13px; margin-top: 4px;\">PitchCraft 10-Slide Blueprint • Target: ")
            .append(v.getTargetCustomer()).append("</div>\n");
        html.append("    </div>\n");
        html.append("    <div><span class=\"badge\">").append(v.getDecisionTier()).append(" (")
            .append(v.getOverallScore()).append("/100)</span></div>\n");
        html.append("  </div>\n");

        // Slides
        html.append("  <div class=\"slide-card\">\n");
        html.append("    <div class=\"slide-title\">Slide 1 & 2: Executive Summary & Core Problem</div>\n");
        html.append("    <p><strong>Problem Statement:</strong> ").append(v.getProblemStatement()).append("</p>\n");
        html.append("  </div>\n");

        html.append("  <div class=\"slide-card\">\n");
        html.append("    <div class=\"slide-title\">Slide 3 & 4: Proposed Solution & Market Validation</div>\n");
        html.append("    <p><strong>Solution:</strong> ").append(v.getProposedSolution()).append("</p>\n");
        html.append("    <div class=\"grid-2\">\n");
        html.append("      <div class=\"metric-box\"><div class=\"metric-lbl\">Market Validation</div><div class=\"metric-val\">")
            .append(v.getMarketScore()).append("/100</div></div>\n");
        html.append("      <div class=\"metric-box\"><div class=\"metric-lbl\">Technical Feasibility</div><div class=\"metric-val\">")
            .append(v.getFeasibilityScore()).append("/100</div></div>\n");
        html.append("      <div class=\"metric-box\"><div class=\"metric-lbl\">Competitive Moat</div><div class=\"metric-val\">")
            .append(v.getCompetitionScore()).append("/100</div></div>\n");
        html.append("      <div class=\"metric-box\"><div class=\"metric-lbl\">Concept Depth</div><div class=\"metric-val\">")
            .append(v.getDepthScore()).append("/100</div></div>\n");
        html.append("    </div>\n");
        html.append("  </div>\n");

        html.append("  <div class=\"slide-card\">\n");
        html.append("    <div class=\"slide-title\">Slide 5: Business Model & Monetization</div>\n");
        html.append("    <p>").append(v.getBusinessModel()).append("</p>\n");
        html.append("  </div>\n");

        html.append("  <div class=\"slide-card\">\n");
        html.append("    <div class=\"slide-title\">Slide 6 & 7: SWOT Matrix & Critical Failure Risks</div>\n");
        html.append("    <div class=\"grid-2\">\n");
        html.append("      <div class=\"metric-box\"><div class=\"metric-lbl\">Strengths</div><div>").append(v.getStrengths()).append("</div></div>\n");
        html.append("      <div class=\"metric-box\"><div class=\"metric-lbl\">Weaknesses</div><div>").append(v.getWeaknesses()).append("</div></div>\n");
        html.append("      <div class=\"metric-box\"><div class=\"metric-lbl\">Opportunities</div><div>").append(v.getOpportunities()).append("</div></div>\n");
        html.append("      <div class=\"metric-box\"><div class=\"metric-lbl\">Threats</div><div>").append(v.getThreats()).append("</div></div>\n");
        html.append("    </div>\n");
        html.append("    <p style=\"margin-top: 12px; color: #DC2626;\"><strong>Critical Failure Risks:</strong> ")
            .append(v.getCriticalRisks()).append("</p>\n");
        html.append("  </div>\n");

        html.append("  <div class=\"slide-card\">\n");
        html.append("    <div class=\"slide-title\">Slide 8 & 9: CapTable Equity & Investment Round</div>\n");
        html.append("    <div class=\"grid-2\">\n");
        html.append("      <div class=\"metric-box\"><div class=\"metric-lbl\">Founders Split</div><div class=\"metric-val\">")
            .append(v.getFounderEquity()).append("%</div></div>\n");
        html.append("      <div class=\"metric-box\"><div class=\"metric-lbl\">ESOP Talent Pool</div><div class=\"metric-val\">")
            .append(v.getEsopPool()).append("%</div></div>\n");
        html.append("      <div class=\"metric-box\"><div class=\"metric-lbl\">Pre-Money Valuation</div><div class=\"metric-val\">")
            .append(CURRENCY.format(v.getPreMoneyValuation())).append("</div></div>\n");
        html.append("      <div class=\"metric-box\"><div class=\"metric-lbl\">Investment Round Ask</div><div class=\"metric-val\" style=\"color: #4F46E5;\">")
            .append(CURRENCY.format(v.getInvestmentAmount())).append("</div></div>\n");
        html.append("    </div>\n");
        html.append("  </div>\n");

        html.append("  <div class=\"slide-card\">\n");
        html.append("    <div class=\"slide-title\">Slide 10: BurnWatch Financial Health & Cash Runway</div>\n");
        html.append("    <div class=\"grid-2\">\n");
        html.append("      <div class=\"metric-box\"><div class=\"metric-lbl\">Current Cash Reserves</div><div class=\"metric-val\">")
            .append(CURRENCY.format(v.getCurrentCashBalance())).append("</div></div>\n");
        html.append("      <div class=\"metric-box\"><div class=\"metric-lbl\">Estimated Cash Runway</div><div class=\"metric-val\" style=\"color: #059669;\">")
            .append(v.getRunwayMonths()).append(" Months</div></div>\n");
        html.append("    </div>\n");
        html.append("  </div>\n");

        html.append("</div>\n</body>\n</html>");

        Path path = Paths.get(destinationPath);
        Files.writeString(path, html.toString(), StandardCharsets.UTF_8);
        return path;
    }
}
